// app/data/projectsData.ts

// Mendefinisikan "cetakan" atau struktur untuk setiap objek proyek
export interface Project {
  image: string;
  title: string;
  category: string;
  description: string;
  features: string[]; // <-- Properti baru untuk fitur sudah ditambahkan
  techStack: string[];
  liveDemoUrl: string;
  repoUrl: {
    frontend?: string;
    backend?: string;
    main?: string;
  };
  collectionUrl?: string;
}

// Daftar semua proyek Anda
export const projects: Project[] = [
  {
    image: "/projects/java-nocturnals.jpg",
    title: "Java Nocturnals NFT Gallery",
    category: "Full-Stack dApp",
    description: "This project delivers an end-to-end NFT collection of nine AI-generated artworks, each depicting Javanese nocturnal fauna in a distinctive Neon-Punk style.",
    features: [
      "Professional Smart Contract (ERC721) with Solidity & OpenZeppelin, ensuring secure and standardized NFT deployment.",
      "Visual assets and metadata are generated by Generative AI, enabling the creation of scalable and unique digital content.",
      "Interactive frontend (dApp) built with React & TypeScript, providing an engaging and user-friendly experience.",
      "Decentralized storage on IPFS via Pinata guarantees accessibility and resilience."
    ],
    techStack: ["Solidity", "Hardhat", "React", "TypeScript", "Ethers.js", "IPFS", "AI"],
    liveDemoUrl: "https://java-nocturnals-gallery.vercel.app",
    collectionUrl: "https://testnet.rarible.com/denasurya",
    repoUrl: {
      frontend: "https://github.com/denasurya/java-nocturnals-gallery",
      backend: "https://github.com/denasurya/java-nocturnals-contract",
    }
  },
  {
    image: "/projects/cipta-ajar.jpg",
    title: "Cipta Ajar AI",
    category: "AI Web Application",
    description: "An intelligent web application designed to empower educators in Indonesia by automating and simplifying the creation of teaching tools, saving teachers time and effort.",
    features: [
      "Generates four types of teaching materials (Lesson Plans, Modules, Worksheets, and Question Banks) in real-time using the Google Gemini API.",
      "In-depth output customization, covering educational levels (Elementary to High/Vocational School), subjects, topics, and down to the precise allocation of lesson hours.",
      "A professional interface with 'Copy Text' and 'Download' functionalities."
    ],
    techStack: ["Next.js", "React", "Tailwind CSS", "Gemini API"],
    liveDemoUrl: "https://ciptaajar-denasurya.vercel.app/",
    repoUrl: {
      main: "https://github.com/denasurya/Cita-Ajar-demo-01",
    }
  },
  {
    image: "/projects/vocality.jpg",
    title: "VOCALITY - AI Voice Training",
    category: "Interactive Web App",
    description: "An interactive web application to improve English speaking skills using AI, tailored for junior high school students.",
    features: [
      "Dual practice modes: 'Reading Practice' and 'Image Description'.",
      "Text and image content are generated in real-time by the Gemini API.",
      "Comprehensive AI-powered assessment covering pronunciation, grammar, and vocabulary.",
      "Adjustable-speed audio benchmark for pronunciation comparison (Web Speech API)."
    ],
    techStack: ["HTML5", "CSS3", "JavaScript", "Vercel Serverless", "Gemini API"],
    liveDemoUrl: "https://vocality-training.vercel.app/",
    repoUrl: {
      main: "https://github.com/denasurya/vocaliti-final",
    }
  }
];